spring.application.name=PropertyTechApiGateway
server.port=6060
eureka.client.serviceUrl.defaultZone=http://localhost:5050/eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


spring.main.web-application-type=reactive

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


spring.cloud.gateway.routes[0].id=PropertyTechSearch
spring.cloud.gateway.routes[0].uri=lb://PROPERTYTECHSEARCH
spring.cloud.gateway.routes[0].predicates[0]=Path=/propertytechsearch/**
spring.cloud.gateway.routes[0].filters=PropertyApiGatewayFilter


spring.cloud.gateway.routes[1].id=PropertyTechSecurity
spring.cloud.gateway.routes[1].uri=lb://PROPERTYTECHSECURITY
spring.cloud.gateway.routes[1].predicates[0]=Path=/propertytechsecurity/**
spring.cloud.gateway.routes[1].filters=PropertyApiGatewayFilter


spring.cloud.gateway.httpserver.wiretap=true 
spring.cloud.gateway.httpclient.wiretap=true
eureka.instance.hostname=localhost




logging.level.org.springframework.security=DEBUG